### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by monalisa62003** [arnab2206/Online-Picture-Gallery-PHP-MySQL-Project#1]
so an admin has no gallery of their own? (had to guess the password was admin! wish people would include this in their code otherwise it could be useless)

**Comment by arnab2206** [comment]
Will try to fix it when I'll get time - thanks for raising it.

P.S.: It was just a course project from initial days in university, didn't know much about coding then. xD

**Comment by monalisa62003** [comment]
Hey, sorry if I was blunt, trying to set up a members area of my site with a gallery for albums and a quiz with prizes,so I want people to be aBle to upload pictures of them for people to see to encourage them to join etc 

I used a login code that has an admin already in, so I just need to change the wording around. I'm only on basic learning by self
